[package]
name = "reedline"
version = "0.11.0"
authors = ["JT <jonathan.d.turner@gmail.com>"]
edition = "2021"
description = "A readline-like crate for CLI text input"
license = "MIT"
repository = "https://github.com/nushell/reedline"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = true

[[bin]]
name = "reedline"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
clipboard = { version = "0.5.0", optional = true }
crossterm = { version = "0.25.0", features = ["serde"] }
itertools = "0.10.3"
nu-ansi-term = "0.46.0"
serde = { version = "1.0", features = ["derive"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"
strip-ansi-escapes = "0.1.1"
strum = "0.24"
strum_macros = "0.24"
fd-lock = "3.0.3"
rusqlite = { version = "0.28.0", optional = true }
serde_json = { version = "1.0.79", optional = true }
gethostname = { version = "0.2.3", optional = true }
thiserror = "1.0.31"
crossbeam = { version = "0.8.2", optional = true }

[dev-dependencies]
tempfile = "3.3.0"
pretty_assertions = "1.1.0"
rstest = { version = "0.15.0", default-features = false }

[features]
system_clipboard = ["clipboard"]
bashisms = []
external_printer = ["crossbeam"]
sqlite = ["rusqlite/bundled", "serde_json", "gethostname"]
sqlite-dynlib = ["rusqlite", "serde_json", "gethostname"]

